[package]
name = "kaori"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
ordered-float = "5.1.0"
criterion = "0.5"

[profile.release]
debug = false
opt-level = 3
codegen-units = 1   